deploy:
  provider: s3
  access_key_id: "AKIAIUBLXQCJJUUQLUSQ"
  secret_access_key:
    secure: "hO6U5FUrL6usEb4ZAIX797c3BqjPmUfsa6AIiwHPSi+ffUhw6P0yxdJNqJE7AMMQyHTjcXvoD86JBdEO1x2usISruKD/5NvaTxcvjuLHREAMaa1cvxizP29q3Okm0ugqlXcGzCFeR0LRQXP+45QwYSi7BNw/lxvJGlxhgUhCklNPprfaJQSQ7fLnHZChc5bfnAPlDDs4W1xpvIKGDIIz9RCfKT3zLobUFjzOqjXIEV3DxvLYVtbXgFe/QrJS/ucTaIj6K71h4jXEUUV4z7pZmG2BpkbdGr/r61Zd8D8MeZ9vCQO+FG+sDWVAYzvbq55VxCQG2aDRgA041uYYUJEsrOfA06pEsGk1WXSaqHWB75SAkLvsHxC+sht2RvQHpKmtN0kGaUGECF1SiVi995vJkneSph//9LqqrDejA0eDDnpTh/RAOBCuWuJL/xYJwo7LrO8dLt8b31EdfIz3ZJV6y6QSW+TKm456D2ShwV913WyLWaJjwR/LCo6+9O35H8xpfxPVQaXLwIZP/8RGJ97DNDM7wP3T61JMVaWRFThm2ChKlWazhoU4iL44MoqPaa17s27oipi1dTwto4Y20JTT2eGOjmNiNTbenH4V+4lkVoMNubNxrmbfq25tSIbF91YWRzJsIYZAJfBh0Tj3Bvplc2w6jO2fGGYs1YCggGRSlCQ="
  bucket: "codefry-portfolio"

