language: node_js
directories:
  - node_modules
deploy:
  provider: s3
  access_key_id: "AKIAIUBLXQCJJUUQLUSQ"
  secret_access_key:
    secure: "ZO9WVbw/Mc+hBa3E/GVcX34T/NH2UKdgU4WKIzq1ega4p2Lc8dlgnsAqVfmxNpASdTlh0oWh+4TWwo9QLnDstNUomg3dFl3TezsJkP2jvjnAZwNK9aj5kAM6PcSx2mpTEgMQ/3TqEvezic0AinPr59rK0GUYJGPQCAjPiqCLX0x5jpQQqb8SqtPRyw3JUUiwmKAyYb9WFQt3Q0aB00HahnrnfnKUf66kVJrPDXmCBZ2lHNZB0wqsfE88X0i+WEwtIJHawkzwNfYKy0kbxYP46CevQQaP95QX6XPcwJvASVeO2t6hCei7ITXV0PKzfZDtnLK0UhQfNBbVDvxfb7JPv/l3hk82aET2Cvw/jH7khObK0Bp/KNVCn/juhuyx9lnyrlPQhchLfEED5n6Prl6tumIr9bfYqrD2/TuNg1PdLHrmt462p2crghv3OfVGzzmM5YygeUDiXecnPPdMGR7/8kdtgMeZGGPDg6D6p7KWVFWeG7PdW9aMvIctaVaof/7iF/VAafpLUapog5hkxm2gqoN1S/xM/wTWO3pi/IWN48GVllQbCwZmZ8DDAO7O9XYQJeR7nr+ij6a97W22g10stRFw7d+qmnlXDSfnxNhCY9tL5nD1NfW8rl7HtAW2lqp5TqylBB3Nuu9m4cEUCKwh0EwqVknP1PdIXpNYqzPW1JU="
  bucket: "codefry-portfolio"

